version: '3.5'
services:
  minio:
    image: minio/minio:latest
    container_name: fileP2P-minio
    volumes:
      - data:/data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090"
    restart: always

volumes:
  data: